### PR TITLE
fix: correct pip command typo and update gensim version in Lesson 5 NLP

### LINKED ISSUE #632: NLP Requirements Error
When following the instructions in \lessons\5-NLP\README, there is a typo in the pip command. It should say pip install -r requirements-pytorch.txt instead of pip install -r requirements-torch.txt as the latter file does not exist. Also, running the fixed command gives the following terminal error:
C:\Users\aaron\AI-For-Beginners\lessons\5-NLP>pip install -r requirements-pytorch.txt
Collecting gensim==3.8.3 (from -r requirements-pytorch.txt (line 1))
  Downloading gensim-3.8.3.tar.gz (23.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.4/23.4 MB 2.9 MB/s  0:00:08
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\dist.py:765: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      running dist_info
      creating C:\Users\aaron\AppData\Local\Temp\pip-modern-metadata-bgf4wwzk\gensim.egg-info
      writing C:\Users\aaron\AppData\Local\Temp\pip-modern-metadata-bgf4wwzk\gensim.egg-info\PKG-INFO
      writing dependency_links to C:\Users\aaron\AppData\Local\Temp\pip-modern-metadata-bgf4wwzk\gensim.egg-info\dependency_links.txt
      writing requirements to C:\Users\aaron\AppData\Local\Temp\pip-modern-metadata-bgf4wwzk\gensim.egg-info\requires.txt
      writing top-level names to C:\Users\aaron\AppData\Local\Temp\pip-modern-metadata-bgf4wwzk\gensim.egg-info\top_level.txt
      writing manifest file 'C:\Users\aaron\AppData\Local\Temp\pip-modern-metadata-bgf4wwzk\gensim.egg-info\SOURCES.txt'
      Traceback (most recent call last):
        File "C:\Users\aaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
        File "C:\Users\aaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 175, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 367, in <module>
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)  # type: ignore[return-value]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 202, in run_commands
          dist.run_commands()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 1000, in run_commands
          self.run_command(cmd)
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\dist.py", line 1107, in run_command
          super().run_command(command)
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 1019, in run_command
          cmd_obj.run()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 94, in run
          self.egg_info.run()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 312, in run
          self.find_sources()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 320, in find_sources
          mm.run()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 542, in run
          self.add_defaults()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 580, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\command\sdist.py", line 110, in add_defaults
          super().add_defaults()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 245, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 329, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\aaron\AppData\Local\Temp\pip-build-env-m91cat8j\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 119, in ensure_finalized
          self.finalize_options()
        File "<string>", line 111, in finalize_options
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> gensim

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### PR DESCRIPTION
**Pull request by dcaayushd**
Fixes #632
Two issues fixed in the Lesson 5 NLP setup:

Corrected a typo in README.md: requirements-torch.txt → requirements-pytorch.txt (the former file doesn't exist)
Updated gensim==3.8.3 to gensim>=4.3.0 in requirements-pytorch.txt (the pinned version fails to build on Python 3.10+ due to a NumPy compatibility issue)

### CODE REVIEW

**Comment by dcaayushd** [comment]
@microsoft-github-policy-service agree

**Comment by dcaayushd** [comment]
@leestott please have a look at this.
